runtime: nodejs18
service: covid-dashboard

env_variables:
  NODE_ENV: "production"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

handlers:
  - url: /_next/static
    static_dir: .next/static
    secure: always

  - url: /.*
    script: auto
    secure: always 